### PR TITLE
task handling improvements

### LINKED ISSUE #20: heart health dashboard: fallback option for exercise minutes if user doesn't have a watch
### Problem

the heart health dashboard displays exercise data in one of its grid items. but since only the apple watch seems to be able to contribute data to that, this field will always be empty for those users that don't have a watch

### Solution

we should fall back to step count (which is also collected by the iPhone) if there is no exercise minutes data available for e.g. the past 2 weeks.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #36: charts appear empty if there's only a single data point
### Description

the charts currently don't display anything if there's only a single data point (despite them not being empty, as can be seen by long-pressing and moving a finger across the chart, which should highlight the single data point)

### Reproduction

see above

### Expected behavior

it should display a point mark if there's only a single data point

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #41: "contribute to heart health research" text inexplicably doesn't line-break properly
### Description

don't ask me what's causing this i've looked into it and i have honestly no idea it works fine in spanish it works fine when we create a separate OnboardingView with the exact same content but for some reason it does not work fine with this particular view...

Image

### Reproduction

launch the app on a non-max iPhone

### Expected behavior

it should line-wrap

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #49: surface personalized notifications in-app
### Problem

we currently sometimes send personalized push notifications from the server to the app. currently, these notifications simply open the app when tapped, but there's no way of viewing current/past notifications in the app

### Solution

we should add a thing somewhere, that lets you view some/all of the past notifications

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #52: ECG active task
### Problem

we want the user to take an ECG every now and then

### Solution

we should have an active task that tells the user how to perform an ECG. we could integrate this with HealthKit, by observing the ECG samples and marking the task as completed when we see the new samples.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by lukaskollmer**
# task handling improvements

## :recycle: Current situation & Problem
issue: non-recurring tasks should always stay presented in the app, even if they're not completed on the day they're scheduled. currently, the app does not exhibit this behaviour.

## :gear: Release Notes
- the home tab now displays the current nudge, if available. (it displays either today's nudge, or, if that isn't yet available, yesterday's) (fixes #49)
- we have an ECG task, which when initiated displays the "how to take an ECG" instructions, and auto-completes when the app observes that a new ECG has been added (it can also be marked as complete manually as a fallback) (fixes #52)
- Heart Health Tab:
    - the charts in the health tab should no longer appear empty when containing only a single data point (fixes #36)
    - "Blood Glucose" is now consistently called "Hemoglobin A1c (HbA1c)"
    - nicotine exposure no longer has a chart
    - the Recent Value display in the top-left is improved, and now uses more correct units and also indicates if no data is available
    - sleep durations are properly formatted as eg "5 hr 45 min" instead of "5.666 hr"
    - improved the selection overlay when long-pressing the charts
    - fixed the sleep data chart getting stuck in a "Processing Data" state if no data was available
    - the health dashboard overall and some metrics' sub-pages now show an explainer wrt the respective required data sources
    - the health dashboard now intelligently selects step counts as a fallback for exercise minutes, if none are available for the past week (fixes #20)
    - fixed all scoring rules (except for the new step count rule)
    - overall UI improvements (eg padding around the chart, fonts, etc)
    - the charts now have more x axis marks, to better indicate the time range
- the "today's tasks" list on the home tab will now also include non-recurring past events that haven't been completed yet, regardless of how far back they originally were scheduled
- (internal) initated task action handling is now consolidated into a single view modifier
- performing and completing an "always available" task will now, in some cases, auto-complete an upcoming regularly scheduled task with the same action, making the behaviour identical to as if the user had direclty triggered it via the regularly scheduled event
- disabled the "Sign in With Apple" option (for the time being)
- added a couple of missing spanish translations
- updated the website URL links
- removed both "Study Details" buttons from the account sheet; tapping the "Enrolled Study: MHC" row now simply opens the website
- fixed that the logout button would be disabled sometimes
- some iOS 26 adjustments (liquid glass)
- fixes to FHIR observations (effectiveDate was missing for some SensorKit data)
- "Contribute to Heart Health Research" is now just "Contribute to Research" (fixes #41)

## :books: Documentation
n/a

## :white_check_mark: Testing
*todo*

### Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukaskollmer** [comment]
@PSchmiedmayer i ended up making some more fundamental changes here; essentially all task-performing-related logic is now lifted out of the views themselves and instead handled by a dedicated `@PerformTask` property wrapper; this covers initiating a task, presentation of the task's specific UI, and optionally also marking any associated events as complete.

the way this works is that we have the concept of a "TaskPerformingAnchor", which is a part of the app (injected into the view hierarchy) that can respond to and handle initiating a user-interactive task (eg: "answer this questionnaire", "take an ECG", etc), for any tasks being initiated from the part of the view hierarchy for which the anchor is responsible.
individual views within the hierarchy don't need to implement each task type's specific logic (ie, presenting all the different sheets, uploading their results) on their own and instead simply use the `@PerformTask` API to tell the nearst Anchor what to do.

additionally, we now, when the user completes an always-available task, also attempt to identify and complete an upcoming event that would've triggered the same task. for example, if you have an ECG scheduled for tomorrow, and you tap the "Take ECG" button today, and successfully record an ECG, we now complete tomorrow's event in advance, causing SpeziStudy to schedule a new ECG task 5 days from now (instead of keeping tomorrow's task uncompleted and unnecessarily prompting the user again; or instead of marking tomorrow's task as completed and triggering a new one 5 days from then ie 6 days from now).

imo, this makes it significantly easier for us to present/initiate user-actionable tasks from effectively arbitracy parts of the app, without having to duplicate a bunch of logic & boilerplate all over the place. additionally, we can safely offer "always available" tasks, without having to worry about that possibly messing up the overall study schedule.

File: MyHeartCounts/Account/AccountSheet.swift
Comment (PSchmiedmayer) [inline MyHeartCounts/Account/AccountSheet.swift:1]: Might be good to address all periphery warnings here and across the codebase and treat them all as errors. If they are to false positives we can add inline comments for them.

File: MyHeartCounts/Task Handling/PerformTaskAnchor.swift [hunk 1]
```diff
@@ -0,0 +1,252 @@
...
+// This source file is part of the My Heart Counts iOS application based on the Stanford Spezi Template Application project
+//
+// SPDX-FileCopyrightText: 2025 Stanford University
+//
+// SPDX-License-Identifier: MIT
+//
+
+// swiftlint:disable all
+
+// TODO terminology here!!! (perform vs present vs active! task vs action!)
```
Comment (PSchmiedmayer) [inline MyHeartCounts/Task Handling/PerformTaskAnchor.swift:11]: I like the perform wording here; indicates a longer running process compared to present/activate.

File: MyHeartCounts/Task Handling/PerformTaskAnchor.swift
Comment (PSchmiedmayer) [inline MyHeartCounts/Task Handling/PerformTaskAnchor.swift:1]: Nice idea here!

File: MyHeartCounts/Home Tab/DailyNudge.swift [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+//
+
+@preconcurrency import FirebaseFirestore
+import Foundation
+import SwiftUI
+
+
+@MainActor
+@propertyWrapper
+struct DailyNudge: DynamicProperty {
```
Comment (PSchmiedmayer) [inline MyHeartCounts/Home Tab/DailyNudge.swift:16]: Nice setup here!

File: MyHeartCounts/Task Handling/Active Tasks/ECG/ECGInstructions.swift
Comment (PSchmiedmayer) [inline MyHeartCounts/Task Handling/Active Tasks/ECG/ECGInstructions.swift:1]: Nice setup with the automatic completion; so cool to see the simple usage of SpeziHealthKit here!

**Review by PSchmiedmayer — APPROVED** [review]
Looks great; thank you for all the work here @lukaskollmer; only had a few comments along the way 👍

File: MyHeartCounts/Account/Demographics/DemographicsAccountKeys.swift [hunk 3]
```diff
@@ -6,8 +6,6 @@
 // SPDX-License-Identifier: MIT
 //
 
-// swiftlint:disable all
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply MyHeartCounts/Account/Demographics/DemographicsAccountKeys.swift:9]: agreed; this one was literally just an oversight, there was only a single line that actually needed to be changed

File: MyHeartCounts/Task Handling/PerformTaskAnchor.swift (hunk 1 above)
Comment (PSchmiedmayer) [reply MyHeartCounts/Task Handling/PerformTaskAnchor.swift]: Sound good; thank you!
